--  age (in seconds) at which the explosion actor deletes itself
--  make sure this exceedes the age of all effects
LifeSpan = 3.0

Sprites =
{
	{
		Name = "turretlaser_fire",

		States =
		{
			Normal =
			{
				Frames =
				{
					{ texture = "effects/media/LaserFX_00000.dds" },
					{ texture = "effects/media/LaserFX_00001.dds" },
					{ texture = "effects/media/LaserFX_00002.dds" },
					{ texture = "effects/media/LaserFX_00003.dds" },
					{ texture = "effects/media/LaserFX_00004.dds" },
					{ texture = "effects/media/LaserFX_00005.dds" },
					{ texture = "effects/media/LaserFX_00006.dds" },
					{ texture = "effects/media/LaserFX_00007.dds" },
					{ texture = "effects/media/LaserFX_00008.dds" },
					{ texture = "effects/media/LaserFX_00009.dds" },
					{ texture = "effects/media/LaserFX_00010.dds" },
					{ texture = "effects/media/LaserFX_00011.dds" },
					{ texture = "effects/media/LaserFX_00012.dds" },
					{ texture = "effects/media/LaserFX_00013.dds" },
					{ texture = "effects/media/LaserFX_00014.dds" },
					{ texture = "effects/media/LaserFX_00015.dds" },
					{ texture = "effects/media/LaserFX_00016.dds" },
					{ texture = "effects/media/LaserFX_00017.dds" },
					{ texture = "effects/media/LaserFX_00018.dds" },
					{ texture = "effects/media/LaserFX_00019.dds" },
					{ texture = "effects/media/LaserFX_00020.dds" },
					{ texture = "effects/media/LaserFX_00021.dds" },
					{ texture = "effects/media/LaserFX_00011.dds" },
					{ texture = "effects/media/LaserFX_00012.dds" },
                    { texture = "effects/media/LaserFX_00013.dds" },
					{ texture = "effects/media/LaserFX_00014.dds" },
					{ texture = "effects/media/LaserFX_00015.dds" },
					{ texture = "effects/media/LaserFX_00016.dds" },
					{ texture = "effects/media/LaserFX_00017.dds" },
					{ texture = "effects/media/LaserFX_00018.dds" },
					{ texture = "effects/media/LaserFX_00019.dds" },
					{ texture = "effects/media/LaserFX_00020.dds" },
					{ texture = "effects/media/LaserFX_00021.dds" },
					{ texture = "effects/media/LaserFX_00011.dds" },
					{ texture = "effects/media/LaserFX_00012.dds" },
                    { texture = "effects/media/LaserFX_00013.dds" },
					{ texture = "effects/media/LaserFX_00014.dds" },
					{ texture = "effects/media/LaserFX_00015.dds" },
					{ texture = "effects/media/LaserFX_00016.dds" },
					{ texture = "effects/media/LaserFX_00017.dds" },
					{ texture = "effects/media/LaserFX_00018.dds" },
					{ texture = "effects/media/LaserFX_00019.dds" },
					{ texture = "effects/media/LaserFX_00020.dds" },
					{ texture = "effects/media/LaserFX_00021.dds" },
					{ texture = "effects/media/LaserFX_00011.dds" },
					{ texture = "effects/media/LaserFX_00012.dds" },
                    { texture = "effects/media/LaserFX_00013.dds" },
					{ texture = "effects/media/LaserFX_00014.dds" },
					{ texture = "effects/media/LaserFX_00015.dds" },
					{ texture = "effects/media/LaserFX_00016.dds" },
					{ texture = "effects/media/LaserFX_00017.dds" },
					{ texture = "effects/media/LaserFX_00018.dds" },
					{ texture = "effects/media/LaserFX_00019.dds" },
					{ texture = "effects/media/LaserFX_00020.dds" },
					{ texture = "effects/media/LaserFX_00021.dds" },
					{ texture = "effects/media/LaserFX_00011.dds" },
					{ texture = "effects/media/LaserFX_00012.dds" },
                    { texture = "effects/media/LaserFX_00013.dds" },
					{ texture = "effects/media/LaserFX_00014.dds" },
					{ texture = "effects/media/LaserFX_00015.dds" },
					{ texture = "effects/media/LaserFX_00016.dds" },
					{ texture = "effects/media/LaserFX_00017.dds" },
					{ texture = "effects/media/LaserFX_00018.dds" },
					{ texture = "effects/media/LaserFX_00019.dds" },
					{ texture = "effects/media/LaserFX_00020.dds" },
					{ texture = "effects/media/LaserFX_00021.dds" },
					{ texture = "effects/media/LaserFX_00011.dds" },
					{ texture = "effects/media/LaserFX_00012.dds" },
                    { texture = "effects/media/LaserFX_00013.dds" },
					{ texture = "effects/media/LaserFX_00014.dds" },
					{ texture = "effects/media/LaserFX_00015.dds" },
					{ texture = "effects/media/LaserFX_00016.dds" },
					{ texture = "effects/media/LaserFX_00017.dds" },
					{ texture = "effects/media/LaserFX_00018.dds" },
					{ texture = "effects/media/LaserFX_00019.dds" },
					{ texture = "effects/media/LaserFX_00020.dds" },
					{ texture = "effects/media/LaserFX_00021.dds" },
					{ texture = "effects/media/LaserFX_00011.dds" },
					{ texture = "effects/media/LaserFX_00012.dds" },
                    { texture = "effects/media/LaserFX_00013.dds" },
					{ texture = "effects/media/LaserFX_00014.dds" },
					{ texture = "effects/media/LaserFX_00015.dds" },
					{ texture = "effects/media/LaserFX_00016.dds" },
					{ texture = "effects/media/LaserFX_00017.dds" },
					{ texture = "effects/media/LaserFX_00018.dds" },
					{ texture = "effects/media/LaserFX_00019.dds" },
					{ texture = "effects/media/LaserFX_00020.dds" },
					{ texture = "effects/media/LaserFX_00021.dds" },
					{ texture = "effects/media/LaserFX_00011.dds" },
					{ texture = "effects/media/LaserFX_00012.dds" },
                    { texture = "effects/media/LaserFX_00013.dds" },
					{ texture = "effects/media/LaserFX_00014.dds" },
					{ texture = "effects/media/LaserFX_00015.dds" },
					{ texture = "effects/media/LaserFX_00016.dds" },
					{ texture = "effects/media/LaserFX_00017.dds" },
					{ texture = "effects/media/LaserFX_00018.dds" },
					{ texture = "effects/media/LaserFX_00019.dds" },
					{ texture = "effects/media/LaserFX_00020.dds" },
					{ texture = "effects/media/LaserFX_00021.dds" },
					{ texture = "effects/media/LaserFX_00011.dds" },
					{ texture = "effects/media/LaserFX_00012.dds" },
                    { texture = "effects/media/LaserFX_00013.dds" },
					{ texture = "effects/media/LaserFX_00014.dds" },
					{ texture = "effects/media/LaserFX_00015.dds" },
					{ texture = "effects/media/LaserFX_00016.dds" },
					{ texture = "effects/media/LaserFX_00017.dds" },
					{ texture = "effects/media/LaserFX_00018.dds" },
					{ texture = "effects/media/LaserFX_00019.dds" },
					{ texture = "effects/media/LaserFX_00020.dds" },
					{ texture = "effects/media/LaserFX_00021.dds" },
					{ texture = "effects/media/LaserFX_00011.dds" },
					{ texture = "effects/media/LaserFX_00012.dds" },
					{ texture = "effects/media/LaserFX_00012.dds", colour = { 1, 1, 1, 0.0 }, duration = 3 }, -- just makes a blank frame long enough to last the rest of the effect

					duration = 0.05,
					blendColour = false,
					blendCoordinates = false,
				},
				--RandomPlayLength = 2,
				NextState = "Normal",
			},
		},
	},
}
SoundEvent = "effects/fire_laser.lua"
Effects =
{

	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 75, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0.0,
		Sprite = "turretlaser_fire",
		Additive = false,
		TimeToLive = 3,
		Angle = -90,
		InitialSize = 5,
		ExpansionRate = 0,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		KillParticleOnEffectCancel = true,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 255 },
	},
--[[	{
		Type = "bullettime",
		TimeToTrigger = 0,
		TimeToContinue = 1.5,
		Speed = 0.5,
	},
]]
}
